# https://e2b.dev/docs/sandbox-template

# Dockerfile to use for the template
dockerfile = "e2b.Dockerfile"

# Name of the template (optional)
name = "aider-agent"

# Start command (optional)
start_cmd = "/bin/bash"
